AllCops:
  RunRailsCops: true

# Offense count: 1
Lint/Eval:
  Enabled: false

## Offense count: 2
#Lint/HandleExceptions:
#  Enabled: false
#
## Offense count: 1
#Lint/ParenthesesAsGroupedExpression:
#  Enabled: false
#
## Offense count: 1
## Cop supports --auto-correct.
#Lint/RescueException:
#  Enabled: false

## Offense count: 2
#Lint/ShadowingOuterLocalVariable:
#  Enabled: false

## Offense count: 4
## Cop supports --auto-correct.
#Lint/StringConversionInInterpolation:
#  Enabled: false

## Offense count: 4
#Lint/UnderscorePrefixedVariableName:
#  Enabled: false

## Offense count: 5
## Cop supports --auto-correct.
#Lint/UnusedBlockArgument:
#  Enabled: false
#
## Offense count: 10
## Cop supports --auto-correct.
#Lint/UnusedMethodArgument:
#  Enabled: false
#
## Offense count: 1
#Lint/UselessAssignment:
#  Enabled: false

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 140

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 5

# Offense count: 39
# Configuration parameters: AllowURI.
Metrics/LineLength:
  Max: 140

# Offense count: 22
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 25

## Offense count: 2
## Cop supports --auto-correct.
## Configuration parameters: EnforcedStyle, SupportedStyles, Include.
#Rails/ActionFilter:
#  Enabled: false
#
## Offense count: 1
## Configuration parameters: Include.
#Rails/DefaultScope:
#  Enabled: false
#
## Offense count: 1
## Cop supports --auto-correct.
#Rails/Delegate:
#  Enabled: false
#
## Offense count: 5
## Configuration parameters: Include.
#Rails/Output:
#  Enabled: false
#
## Offense count: 3
## Cop supports --auto-correct.
## Configuration parameters: EnforcedStyle, SupportedStyles.
#Style/AccessModifierIndentation:
#  Enabled: false

# Offense count: 5
Style/AccessorMethodName:
  Enabled: false

## Offense count: 2
## Cop supports --auto-correct.
## Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
#Style/AlignHash:
#  Enabled: false

# Offense count: 161
Style/AsciiComments:
  Enabled: false

## Offense count: 28
## Cop supports --auto-correct.
## Configuration parameters: EnforcedStyle, SupportedStyles.
#Style/BarePercentLiterals:
#  Enabled: false

## Offense count: 1
## Cop supports --auto-correct.
#Style/BlockComments:
#  Enabled: false
#
## Offense count: 2
## Cop supports --auto-correct.
#Style/Blocks:
#  Enabled: false

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: false

## Offense count: 17
## Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
#Style/CaseIndentation:
#  Enabled: false

## Offense count: 51
## Configuration parameters: EnforcedStyle, SupportedStyles.
#Style/ClassAndModuleChildren:
#  Enabled: false

## Offense count: 1
## Cop supports --auto-correct.
## Configuration parameters: PreferredMethods.
#Style/CollectionMethods:
#  Enabled: false
#
## Offense count: 1
## Cop supports --auto-correct.
#Style/ColonMethodCall:
#  Enabled: false
#
## Offense count: 3
## Cop supports --auto-correct.
#Style/CommentIndentation:
#  Enabled: false
#
## Offense count: 2
## Cop supports --auto-correct.
#Style/DefWithParentheses:
#  Enabled: false
#
## Offense count: 4
## Cop supports --auto-correct.
#Style/DeprecatedHashMethods:
#  Enabled: false

# Offense count: 144
Style/Documentation:
  Enabled: false

## Offense count: 2
## Cop supports --auto-correct.
## Configuration parameters: EnforcedStyle, SupportedStyles.
#Style/DotPosition:
#  Enabled: false
#
## Offense count: 1
#Style/EachWithObject:
#  Enabled: false

# Offense count: 104
# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Enabled: false

# Offense count: 100
# Cop supports --auto-correct.
Style/EmptyLinesAroundBody:
  Enabled: false

## Offense count: 27
## Configuration parameters: MinBodyLength.
#Style/GuardClause:
#  Enabled: false

# Offense count: 65
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  Enabled: false

## Offense count: 2
## Configuration parameters: MaxLineLength.
#Style/IfUnlessModifier:
#  Enabled: false

## Offense count: 4
## Cop supports --auto-correct.
#Style/IndentArray:
#  Enabled: false

## Offense count: 10
## Cop supports --auto-correct.
## Configuration parameters: EnforcedStyle, SupportedStyles.
#Style/IndentHash:
#  Enabled: false

## Offense count: 7
## Cop supports --auto-correct.
#Style/IndentationConsistency:
#  Enabled: false

## Offense count: 28
## Cop supports --auto-correct.
#Style/IndentationWidth:
#  Enabled: false

## Offense count: 6
#Style/Lambda:
#  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Enabled: false

## Offense count: 5
## Cop supports --auto-correct.
#Style/MethodCallParentheses:
#  Enabled: false
#
## Offense count: 20
## Cop supports --auto-correct.
## Configuration parameters: EnforcedStyle, SupportedStyles.
#Style/MethodDefParentheses:
#  Enabled: false
#
## Offense count: 1
#Style/MultilineBlockChain:
#  Enabled: false
#
## Offense count: 3
## Cop supports --auto-correct.
#Style/NegatedIf:
#  Enabled: false
#
## Offense count: 1
## Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
#Style/Next:
#  Enabled: false
#
## Offense count: 1
## Cop supports --auto-correct.
#Style/NilComparison:
#  Enabled: false
#
## Offense count: 1
## Cop supports --auto-correct.
#Style/Not:
#  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 11

## Offense count: 1
## Cop supports --auto-correct.
## Configuration parameters: AllowSafeAssignment.
#Style/ParenthesesAroundCondition:
#  Enabled: false

# Offense count: 28
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/PercentQLiterals:
  Enabled: false

# Offense count: 2
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

## Offense count: 1
## Cop supports --auto-correct.
#Style/RedundantBegin:
#  Enabled: false
#
## Offense count: 2
#Style/RedundantException:
#  Enabled: false
#
## Offense count: 3
## Cop supports --auto-correct.
## Configuration parameters: AllowMultipleReturnValues.
#Style/RedundantReturn:
#  Enabled: false
#
## Offense count: 32
## Cop supports --auto-correct.
#Style/RedundantSelf:
#  Enabled: false
#
## Offense count: 5
## Configuration parameters: MaxSlashes.
#Style/RegexpLiteral:
#  Enabled: false

## Offense count: 9
## Cop supports --auto-correct.
## Configuration parameters: AllowAsExpressionSeparator.
#Style/Semicolon:
#  Enabled: false

## Offense count: 11
## Cop supports --auto-correct.
## Configuration parameters: EnforcedStyle, SupportedStyles.
#Style/SignalException:
#  Enabled: false

## Offense count: 29
## Cop supports --auto-correct.
#Style/SingleSpaceBeforeFirstArg:
#  Enabled: false
#
## Offense count: 5
## Cop supports --auto-correct.
#Style/SpaceAfterComma:
#  Enabled: false

# Offense count: 19
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

## Offense count: 3
## Cop supports --auto-correct.
#Style/SpaceAroundOperators:
#  Enabled: false

## Offense count: 21
## Cop supports --auto-correct.
## Configuration parameters: EnforcedStyle, SupportedStyles.
#Style/SpaceBeforeBlockBraces:
#  Enabled: false

# Offense count: 148
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 12
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: false

# Offense count: 42
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: false

# Offense count: 314
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

## Offense count: 4
## Cop supports --auto-correct.
## Configuration parameters: IgnoredMethods.
#Style/SymbolProc:
#  Enabled: false
#
## Offense count: 1
## Cop supports --auto-correct.
#Style/Tab:
#  Enabled: false
#
# Offense count: 108
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: false

## Offense count: 1
## Cop supports --auto-correct.
## Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
#Style/TrailingComma:
#  Enabled: false

# Offense count: 116
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: false

## Offense count: 3
## Cop supports --auto-correct.
## Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
#Style/TrivialAccessors:
#  Enabled: false
#
## Offense count: 1
#Style/UnlessElse:
#  Enabled: false

# Offense count: 35
# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Enabled: false

## Offense count: 3
## Cop supports --auto-correct.
#Style/WordArray:
#  MinSize: 4
