user: user
# ssl: true
# ssl_key_file: /etc/ssl/sakedev.cyclonelabs.com.ssl.key.pem
# ssl_cert_file: /etc/ssl/sakedev.cyclonelabs.com.ssl.cert.pem
# chdir: /srv/webdata/sakedev.cyclonelabs.com/current
# pid: /srv/webdata/sakedev.cyclonelabs.com/shared/pids/private_pub_thin.pid
# log: /srv/webdata/sakedev.cyclonelabs.com/shared/log/private_pub_thin.log
environment: production
# daemonize: true
port: 7081
rackup: private_pub.ru


